name: ahmed_image_box
description: "A Flutter package for box image inside slider."
version: 0.0.1
homepage: https://github.com/ProManHub/ahmed_image_box.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: